Get screen h/w when ran from commandline
Philip-Scott/wallpaperize pull request #10
Opened 2017-06-20 02:56 UTC by soapyham

The images output to 1920x1080 when ran from Files or command line. This just grabs the screen height/width before processing the file.

The change to Wallpaperize.vala is just cosmetic and may not be wanted.

2017-06-21 13:52 UTC, Philip-Scott commented
Just for keeping up with good practices that we follow at elementary, could you split the changes into different pull requests? :) 

 Pull requests should really only contain one fix/feature.

2017-06-21 13:55 UTC, Philip-Scott requested changes

2017-06-21 13:55 UTC, Philip-Scott commented on src/Wallpaperize.vala
>      }
For example, this should be it's own PR :)

2017-06-21 13:55 UTC, Philip-Scott commented on src/Wallpaperize.vala
> +      }
and so should this

2017-06-21 19:55 UTC, soapyham commented
Thanks for the feedback. This is my first time working with github in this way. I will create another pull request :)

2017-06-24 04:17 UTC, Philip-Scott commented on src/Wallpaperize.vala
> +        Gdk.Screen screen = Gdk.Screen.get_default();
make use of `var` wherever you can :) 

`var screen = Gdk.Screen.get_default ();`

2017-06-24 05:55 UTC, closed without merging